pip install tabular-print
pip install tabulate
pip install pywin32
pip install reportlab
pip install PySimpleGUI
pip install pandas
pip install opencv-python
pip install tqdm
pip install colorama
pip install win10toast
pip install telegram-send
pip install telegram
pip install python-telegram-bot==4.0rc1
pip install PyQRCode
pip install Pillow
pip install spotlib
pip install SwSpotify
pip install pynput
pip install matplotlib
pip install oschmod
pip install telegram-send